### ISSUE TITLE
"Your images are ready" but no indication how to get them

### ISSUE THREAD

**Issue by DanielHeath** [Haidra-Org/Lucid-Creations#117]
Thanks for building this, very cool concept!

After submitting an image to generate and waiting a few minutes, I get 
![image](https://github.com/Haidra-Org/Lucid-Creations/assets/47430/6e830fe0-6775-48c6-9133-3511cb872b75)

There's no indication where the image is or how to view it. 

Am I being daft / missing something obvious?

**Comment by db0** [comment]
Hello, we had a big downtime yesterday while I slept. Should be OK now. Please restart client and try again
