### ISSUE TITLE
Lucid Creations crashes to desktop when injecting a LoRa's trigger words

### ISSUE THREAD

**Issue by onceuponaban** [Haidra-Org/Lucid-Creations#119]
Running the Windows executable of Lucid Creations 2.4.0, trying to use the LoRa trigger word injection feature crashes to desktop.

Steps to reproduce:

1. Open Lucid Creations
2. Navigate to the controls' tab which handle model, TI and LoRa selection
3. Select a LoRa which has available trigger words (I personally ran into the bug while selecting M_Pixel but it seems any with trigger words will apply)
4. Click on the T button

Instead of injecting the trigger words into the prompt, the application crashes.

**Comment by db0** [comment]
Fixed
