### ISSUE TITLE
LC cannot connect to the AI Horde it seems. It says 'AI horde request timed out'.

### ISSUE THREAD

**Issue by dadadies** [Haidra-Org/Lucid-Creations#125]
I am curious how LC is making its connection. The only time I have connection problems is with pypi and github, and it seems to be because they do things through the CMD, (perhaps of pip I dont know). Which for some reason does not work so i can never download anything from either site through CMD. I can only assume LC is using an unusual connection or at least similar to the connections that pypi and github use. I know nothing how any of it works but it seems to be related.

**Comment by db0** [comment]
No I meant that AI horde uses the same http calls as those sites use. Have you checked that your firewall is not blocking the AI horde software?

**Comment by dadadies** [comment]
I have no firewall on. I use only simplewall and its off and windows firewall is always off.

**Comment by db0** [comment]
Can you reach https://aihorde.net/api manually on your browser from where you're having an issue?

**Comment by dadadies** [comment]
Yes i see the page and assume its a documentation of AI horde 2.0. Works fine. While LC is saying AI Horde request time out. The only thing as said previously, is that TOR, pip, and github all have similar connection issues and its only on my laptop while on the phone these things work fine (while i havent tried pip or github through my tablet. So I dont know if that gives any clue on what the possible issue might be.
