### ISSUE TITLE
ControlNet "Select image" button broken on macOS

### ISSUE THREAD

**Issue by codenyte** [Haidra-Org/Lucid-Creations#126]
When I try to use ControlNet and select an image, I expect a file picker to open. Instead, nothing happens. That way, the ControlNet feature is unusable and thus broken on macOS.

**Comment by db0** [comment]
This should work now via the new native godot browser setting

**Comment by db0** [comment]
Did you switch the "Use Godot browse" setting in the options?

**Comment by db0** [comment]
Whoops, forgot to publish 2.6.6. Try with that one please
